version: '3'
services:
  mysql_master:
    container_name: mysql_master
    environment:
      - MYSQL_ROOT_PASSWORD=admin123456
      - MYSQL_DATABASE=test_db
      - MYSQL_USER=test
      - MYSQL_PASSWORD=123456
      - MASTER_SYNC_USER=sync_admin
      - MASTER_SYNC_PASSWORD=sync_admin123456
      - ADMIN_USER=root
      - ADMIN_PASSWORD=admin123456
      - TZ=Asia/Shanghai
    image: mysql8_master:latest
    build:
      context: ./mysql_master
    ports:
      - 4306:3306
    volumes:
      - ./mysql_master/data:/var/lib/mysql
    networks:
      shardingSphere:
        ipv4_address: 192.168.150.10
    restart: always

  mysql_slave1:
    container_name: mysql_slave1
    image: mysql8_slave1:latest
    build:
      context: ./mysql_slave/slave1
    environment:
      - MYSQL_ROOT_PASSWORD=admin123456
      - MYSQL_DATABASE=test_db
      - MYSQL_USER=test
      - MYSQL_PASSWORD=123456
      - MASTER_SYNC_USER=sync_admin
      - MASTER_SYNC_PASSWORD=sync_admin123456
      - ADMIN_USER=root
      - ADMIN_PASSWORD=admin123456
      - MASTER_HOST=192.168.150.10
      - MASTER_PORT=3306
      - TZ=Asia/Shanghai
    ports:
      - 5306:3306
    volumes:
      - "./mysql_slave/slave1/data:/var/lib/mysql"
    restart: always
    networks:
      shardingSphere:
        ipv4_address: 192.168.150.11
    depends_on:
      - mysql_master

  mysql_slave2:
    container_name: mysql_slave2
    image: mysql8_slave2:latest
    build:
      context: ./mysql_slave/slave2
    environment:
      - MYSQL_ROOT_PASSWORD=admin123456
      - MYSQL_DATABASE=test_db
      - MYSQL_USER=test
      - MYSQL_PASSWORD=123456
      - MASTER_SYNC_USER=sync_admin
      - MASTER_SYNC_PASSWORD=sync_admin123456
      - ADMIN_USER=root
      - ADMIN_PASSWORD=admin123456
      - MASTER_HOST=192.168.150.10
      - MASTER_PORT=3306
      - TZ=Asia/Shanghai
    ports:
      - 5307:3306
    volumes:
      - "./mysql_slave/slave2/data:/var/lib/mysql"
    restart: always
    networks:
      shardingSphere:
        ipv4_address: 192.168.150.12
    depends_on:
      - mysql_master

  mysql_slave3:
    container_name: mysql_slave3
    image: mysql8_slave3:latest
    build:
      context: ./mysql_slave/slave3
    environment:
      - MYSQL_ROOT_PASSWORD=admin123456
      - MYSQL_DATABASE=test_db
      - MYSQL_USER=test
      - MYSQL_PASSWORD=123456
      - MASTER_SYNC_USER=sync_admin
      - MASTER_SYNC_PASSWORD=sync_admin123456
      - ADMIN_USER=root
      - ADMIN_PASSWORD=admin123456
      - MASTER_HOST=192.168.150.10
      - MASTER_PORT=3306
      - TZ=Asia/Shanghai
    ports:
      - 5308:3306
    volumes:
      - "./mysql_slave/slave3/data:/var/lib/mysql"
    restart: always
    networks:
      shardingSphere:
        ipv4_address: 192.168.150.13
    depends_on:
      - mysql_master

networks:
  shardingSphere:
    ipam:
      driver: default
      config:
        - subnet: "192.168.150.0/24"